version: 2
pipeline:
  steps:
    - step:
        phase: install
        image: google/dart
        workdir: /app
        cache:
          - pubspec.yaml
          - pubspec.lock
        commands:
          - pub get
          - pub get --offline

    - step:
        phase: build
        name: build
        workdir: /app
        commands:
          - pub upgrade

    - step:
        phase: test
        name: unit tests
        workdir: /app
        commands:
          - pub run test
