version: 2
pipeline:
  steps:
    - step:
        phase: install
        image: google/dart
        cache:
          - pubspec.yaml
          - pubspec.lock
        commands:
          - pub get

    - step:
        phase: build
        name: build
        commands:
          - pub upgrade

    - step:
        phase: test
        name: unit tests
        commands:
          - pub run test
