name: qbcps_flutter
description: A collection of utility classes for testing and offline development.
version: 0.1.0
author: Stephen Beitzel <sbeitzel@pobox.com>
homepage: https://github.com/sbeitzel/qbcps_flutter

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  tuple: ^1.0.2   # Used by MapDB

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.5.0
