name: qbcps_flutter
description: A new Flutter package project.
version: 0.0.1
author: Stephen Beitzel <sbeitzel@pobox.com>
homepage: https://github.com/sbeitzel/qbcps_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

